# Generated by Django 3.2 on 2021-09-22 12:11

import django_mysql.models.fields.bit
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("public_id", models.BigIntegerField(editable=False, unique=True)),
                (
                    "deleted",
                    django_mysql.models.fields.bit.Bit1BooleanField(
                        default=0, null=True
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=django_mysql.models.fields.bit.Bit1BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.BigIntegerField(default=12344, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
        migrations.CreateModel(
            name="Scopes",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("public_id", models.BigIntegerField(editable=False, unique=True)),
                (
                    "deleted",
                    django_mysql.models.fields.bit.Bit1BooleanField(
                        default=0, null=True
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        db_table="scopes_and_roles",
                        related_name="role_scopes",
                        to="users.Roles",
                    ),
                ),
            ],
            options={
                "db_table": "scopes",
            },
        ),
        migrations.AddField(
            model_name="roles",
            name="user",
            field=models.ManyToManyField(
                db_table="user_and_roles",
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
