# Generated by Django 3.2 on 2021-09-22 12:11

import django.utils.timezone
import django_mysql.models.fields.bit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="deleted",
            field=django_mysql.models.fields.bit.Bit1BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="public_id",
            field=models.BigIntegerField(default=1234, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="deleted",
            field=django_mysql.models.fields.bit.Bit1BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="public_id",
            field=models.BigIntegerField(default=1234, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
