# Generated by Django 3.2 on 2021-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20210922_1211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="public_id",
            field=models.BigIntegerField(
                default=3698334677521032, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="public_id",
            field=models.BigIntegerField(
                default=3698334677521032, editable=False, unique=True
            ),
        ),
    ]
